name = "pages"
main = "src/worker.js"
compatibility_date = "2025-04-15"

[vars]
BASE_URL = "https://virtudia.github.io"
ASSET_PATH = "/allbestview"

[[routes]]
pattern = "allbestview.com/page/*"
script = "pages"

[[routes]]
pattern = "allbestview.com/shop/*"
script = "pages"

[[routes]]
pattern = "allbestview.com/asset/*"
script = "pages"

[[routes]]
pattern = "allbestview.com/doc/*"
script = "pages"

[[routes]]
pattern = "allbestview.com/file/*"
script = "pages"
